export const FETCH_RANDOM_POST_REQUEST = "FETCH_RANDOM_PHOTOS_REQUEST";
export const FETCH_RANDOM_POST_SUCCESS = "FETCH_RANDOM_PHOTOS_SUCCESS";
export const FETCH_RANDOM_POST_FAILURE = "FETCH_RANDOM_PHOTOS_FAILURE";
export const FETCH_MORE_RANDOM_POST_REQUEST = "FETCH_MORE_RANDOM_POST_REQUEST";
export const FETCH_MORE_RANDOM_POST_SUCCESS = "FETCH_MORE_RANDOM_POST_SUCCESS";
export const FETCH_MORE_RANDOM_POST_FAILURE = "FETCH_MORE_RANDOM_POST_FAILURE";
export const HIDE_POSTS = "HIDE_POSTS";
export const UNDO_POSTS  = "UNDO_POSTS";




