
export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";
export const FETCH_USER_PHOTO_REQUEST = "FETCH_USER_PHOTO_REQUEST";
export const FETCH_USER_PHOTO_SUCCESS = "FETCH_USER_PHOTO_SUCCESS";
export const FETCH_USER_PHOTO_FAILURE = "FETCH_USER_PHOTO_FAILURE";
export const FETCH_USER_MORE_PHOTO_REQUEST = "FETCH_USER_MORE_PHOTO_REQUEST";
export const FETCH_USER_MORE_PHOTO_SUCCESS = "FETCH_USER_MORE_PHOTO_SUCCESS";
export const FETCH_USER_MORE_PHOTO_FAILURE = "FETCH_USER_MORE_PHOTO_FAILURE";
export const SEARCH_RESULTS = "SEARCH_RESULTS";
